export type Portion = { label: string; price: number };
export type MenuItem = {
  name: string;
  veg: boolean;
  portions: Portion[];
};
export type Category = {
  id: string;
  name: string;
  items: MenuItem[];
};

const sml = (s: number, m: number, l: number): Portion[] => [
  { label: "S", price: s },
  { label: "M", price: m },
  { label: "L", price: l },
];
const flat = (p: number): Portion[] => [{ label: "", price: p }];

export const menu: Category[] = [
  {
    id: "starters",
    name: "Starters",
    items: [
      { name: "Green Salad", veg: true, portions: [{ label: "M", price: 90 }, { label: "L", price: 130 }] },
      { name: "French Fries", veg: true, portions: [{ label: "M", price: 120 }, { label: "L", price: 190 }] },
      { name: "Crispy Veg", veg: true, portions: flat(160) },
      { name: "Chill Salad", veg: true, portions: flat(160) },
      { name: "Chilly Mushroom Dry", veg: true, portions: flat(170) },
    ],
  },
  {
    id: "soup",
    name: "Soup",
    items: [
      { name: "Veg Hot & Sour", veg: true, portions: flat(130) },
      { name: "Chicken Hot & Sour", veg: false, portions: flat(140) },
      { name: "Veg Sweet Corn", veg: true, portions: flat(150) },
      { name: "Chicken Sweet Corn", veg: false, portions: flat(160) },
      { name: "Chicken Manchow", veg: false, portions: flat(160) },
      { name: "Cream of Chicken", veg: false, portions: flat(170) },
      { name: "Cream of Mushroom", veg: true, portions: flat(180) },
    ],
  },
  {
    id: "seafood",
    name: "Sea Food",
    items: [
      { name: "Aikora Fry", veg: false, portions: sml(270, 500, 900) },
      { name: "Aikora Masala", veg: false, portions: sml(270, 500, 900) },
      { name: "Koonthal Fry", veg: false, portions: sml(270, 500, 900) },
      { name: "Koonthal Masala", veg: false, portions: sml(270, 500, 900) },
      { name: "Avoli Fry", veg: false, portions: sml(310, 580, 1100) },
      { name: "Avoli Masala", veg: false, portions: sml(310, 580, 1100) },
      { name: "Avoli Pollichath", veg: false, portions: sml(310, 580, 1100) },
      { name: "Prawns Fry", veg: false, portions: sml(310, 580, 1100) },
      { name: "Prawns Masala", veg: false, portions: sml(310, 580, 1100) },
      { name: "Prawns Roast", veg: false, portions: sml(310, 580, 1100) },
    ],
  },
  {
    id: "beef",
    name: "Beef Items",
    items: [
      { name: "Chilly Beef", veg: false, portions: sml(210, 380, 600) },
      { name: "Beef Masala", veg: false, portions: sml(210, 380, 600) },
      { name: "Beef Fry", veg: false, portions: sml(210, 380, 600) },
      { name: "Beef Chilly", veg: false, portions: sml(210, 380, 600) },
      { name: "Beef Pepper Masala", veg: false, portions: sml(210, 380, 600) },
      { name: "Beef Coconut Fry", veg: false, portions: sml(220, 420, 630) },
      { name: "Beef Kondattam", veg: false, portions: sml(240, 420, 650) },
      { name: "Beef French", veg: false, portions: sml(240, 420, 650) },
    ],
  },
  {
    id: "poultry",
    name: "Poultry Exotics",
    items: [
      { name: "Chicken Kuruma", veg: false, portions: sml(190, 340, 570) },
      { name: "MLB Nadan Chicken Curry", veg: false, portions: sml(190, 340, 570) },
      { name: "Chicken 65", veg: false, portions: sml(190, 340, 570) },
      { name: "Chicken Chettind", veg: false, portions: sml(190, 340, 570) },
      { name: "Chicken Hydrabadi", veg: false, portions: sml(190, 340, 570) },
      { name: "Chilly Chicken Dry", veg: false, portions: sml(190, 340, 570) },
      { name: "Chilly Chicken Gravy", veg: false, portions: sml(190, 340, 570) },
      { name: "Garlic Chicken", veg: false, portions: sml(190, 340, 570) },
      { name: "Ginger Chicken", veg: false, portions: sml(190, 340, 570) },
      { name: "Kadai Chicken", veg: false, portions: sml(190, 340, 570) },
      { name: "Pepper Chicken", veg: false, portions: sml(190, 340, 570) },
      { name: "French Chicken", veg: false, portions: sml(220, 390, 620) },
      { name: "Chicken Kondattam", veg: false, portions: sml(220, 390, 620) },
      { name: "Chicken 2020", veg: false, portions: sml(220, 390, 620) },
      { name: "Butter Chicken", veg: false, portions: sml(230, 400, 630) },
      { name: "Dragon Chicken", veg: false, portions: sml(240, 430, 740) },
    ],
  },
  {
    id: "vegetarian",
    name: "Vegetarian",
    items: [
      { name: "Tomato Fry", veg: true, portions: sml(140, 250, 460) },
      { name: "Green Peas Masala", veg: true, portions: sml(150, 270, 500) },
      { name: "Gobi 65", veg: true, portions: sml(150, 270, 500) },
      { name: "Chili Gobi", veg: true, portions: sml(160, 290, 540) },
      { name: "Gobi Manchurian", veg: true, portions: sml(160, 290, 540) },
      { name: "Kadai Veg", veg: true, portions: sml(160, 290, 540) },
      { name: "Veg Kolhapuri", veg: true, portions: sml(160, 290, 540) },
      { name: "Veg Kuruma", veg: true, portions: sml(160, 290, 540) },
      { name: "Kadai Mushroom", veg: true, portions: sml(180, 330, 600) },
      { name: "Mushroom Masala", veg: true, portions: sml(180, 330, 600) },
      { name: "Pepper Mushroom Masala", veg: true, portions: sml(180, 330, 600) },
      { name: "Chilli Paneer", veg: true, portions: sml(190, 350, 660) },
      { name: "Kadai Paneer", veg: true, portions: sml(190, 350, 660) },
      { name: "Paneer 65", veg: true, portions: sml(190, 350, 660) },
      { name: "Paneer Pepper Masala", veg: true, portions: sml(190, 350, 660) },
      { name: "Paneer Butter Masala", veg: true, portions: sml(200, 370, 680) },
    ],
  },
  {
    id: "chinese",
    name: "Chinese",
    items: [
      { name: "Biriyani Rice", veg: true, portions: [{ label: "S", price: 70 }, { label: "L", price: 90 }] },
      { name: "Ghee Rice", veg: true, portions: flat(90) },
      { name: "Mandi Rice", veg: true, portions: sml(100, 190, 350) },
      { name: "Veg Fried Rice", veg: true, portions: flat(160) },
      { name: "Egg Fried Rice", veg: false, portions: flat(170) },
      { name: "Chicken Fried Rice", veg: false, portions: flat(180) },
      { name: "Schezwan Chicken Fried Rice", veg: false, portions: flat(200) },
      { name: "Mixed Fried Rice", veg: false, portions: flat(220) },
      { name: "Malaysian Fried Rice", veg: false, portions: flat(230) },
      { name: "Veg Noodles", veg: true, portions: flat(160) },
      { name: "Egg Noodles", veg: false, portions: flat(170) },
      { name: "Chicken Noodles", veg: false, portions: flat(180) },
      { name: "Schezwan Chicken Noodles", veg: false, portions: flat(220) },
      { name: "Mixed Noodles", veg: false, portions: flat(220) },
    ],
  },
  {
    id: "breads",
    name: "Breads",
    items: [
      { name: "Kuboos", veg: true, portions: flat(10) },
      { name: "Chappathi", veg: true, portions: flat(12) },
      { name: "Kerala Parotta", veg: true, portions: flat(15) },
      { name: "Nool Porotta", veg: true, portions: flat(16) },
      { name: "Wheat Parotta", veg: true, portions: flat(16) },
      { name: "Tandoor Roti", veg: true, portions: flat(20) },
      { name: "Butter Roti", veg: true, portions: flat(25) },
      { name: "Kulcha", veg: true, portions: flat(30) },
      { name: "Naan", veg: true, portions: flat(30) },
      { name: "Butter Kulcha", veg: true, portions: flat(40) },
      { name: "Garlic Naan", veg: true, portions: flat(40) },
      { name: "Butter Naan", veg: true, portions: flat(40) },
      { name: "Garlic Butter Naan", veg: true, portions: flat(50) },
    ],
  },
  {
    id: "arabian",
    name: "Arabian Grill",
    items: [
      { name: "Dragon Alfaham", veg: false, portions: sml(190, 340, 620) },
      { name: "Al Faham", veg: false, portions: sml(160, 290, 520) },
      { name: "Tandoori Chicken", veg: false, portions: sml(160, 280, 520) },
      { name: "Honey Al Faham", veg: false, portions: sml(170, 300, 570) },
      { name: "Kanthari Alfaham", veg: false, portions: sml(170, 300, 570) },
      { name: "Piri Piri Alfaham", veg: false, portions: sml(170, 310, 590) },
      { name: "Alfaham Pollichathu", veg: false, portions: sml(180, 320, 600) },
      { name: "Shawaya Quarter", veg: false, portions: flat(160) },
      { name: "Shawaya Half", veg: false, portions: flat(290) },
      { name: "Shawaya Full", veg: false, portions: flat(520) },
    ],
  },
  {
    id: "combo",
    name: "Combo Meals",
    items: [
      { name: "Al Faham & Mandi", veg: false, portions: sml(210, 390, 760) },
      { name: "Shawaya & Mandi", veg: false, portions: sml(210, 390, 760) },
      { name: "Kanthari & Mandi", veg: false, portions: sml(220, 410, 780) },
      { name: "Honey Combo", veg: false, portions: sml(220, 410, 780) },
      { name: "Piri Piri Alf & Mandi", veg: false, portions: sml(230, 420, 800) },
      { name: "Pollichath & Mandi", veg: false, portions: sml(240, 440, 820) },
      { name: "Dragon Combo", veg: false, portions: sml(260, 480, 900) },
    ],
  },
  {
    id: "shawarma",
    name: "Shawarma",
    items: [
      { name: "Plate Kuboos", veg: false, portions: flat(120) },
      { name: "Rumali Roll", veg: false, portions: flat(120) },
    ],
  },
  {
    id: "broast",
    name: "Broast",
    items: [
      { name: "Regular Broast", veg: false, portions: sml(170, 290, 550) },
      { name: "Regular 15pc Family", veg: false, portions: flat(810) },
      { name: "Regular 20pc Family", veg: false, portions: flat(1060) },
      { name: "Flaming Hot Broast", veg: false, portions: sml(180, 300, 580) },
      { name: "Flaming Hot 15pc", veg: false, portions: flat(840) },
      { name: "Flaming Hot 20pc", veg: false, portions: flat(1110) },
      { name: "Spicy Broast", veg: false, portions: sml(190, 310, 600) },
      { name: "Spicy 15pc", veg: false, portions: flat(860) },
      { name: "Spicy 20pc", veg: false, portions: flat(1160) },
    ],
  },
  {
    id: "biriyani",
    name: "Biriyani",
    items: [
      { name: "Malabar Dum", veg: false, portions: [{ label: "Half", price: 120 }, { label: "Full", price: 180 }] },
      { name: "Beef Biriyani", veg: false, portions: [{ label: "Half", price: 140 }, { label: "Full", price: 200 }] },
      { name: "Egg Biriyani", veg: false, portions: flat(150) },
      { name: "Veg Biriyani", veg: true, portions: flat(160) },
      { name: "Mutton Biriyani", veg: false, portions: flat(300) },
      { name: "Alkora Biriyani", veg: false, portions: flat(290) },
      { name: "Prawns Biriyani", veg: false, portions: flat(320) },
    ],
  },
  {
    id: "buckets",
    name: "Buckets",
    items: [
      { name: "Shawaya Bucket", veg: false, portions: flat(800) },
      { name: "Alfaham Bucket", veg: false, portions: flat(800) },
      { name: "Kanthari Alf Bucket", veg: false, portions: flat(820) },
      { name: "Piri Piri Alf Bucket", veg: false, portions: flat(820) },
      { name: "Honey Alf Bucket", veg: false, portions: flat(820) },
      { name: "Pollichath Alf Bucket", veg: false, portions: flat(850) },
      { name: "Dragon Alf Bucket", veg: false, portions: flat(920) },
      { name: "Chicken Biriyani Bucket", veg: false, portions: flat(930) },
      { name: "Beef Biriyani Bucket", veg: false, portions: flat(990) },
      { name: "Veg Fried Rice Bucket", veg: true, portions: flat(850) },
      { name: "Egg Fried Rice Bucket", veg: false, portions: flat(900) },
      { name: "Chicken Fried Rice Bucket", veg: false, portions: flat(950) },
      { name: "Mixed Fried Rice Bucket", veg: false, portions: flat(1200) },
      { name: "Schezwan Fried Rice Bucket", veg: false, portions: flat(1100) },
      { name: "Malaysian Fried Rice Bucket", veg: false, portions: flat(1200) },
    ],
  },
];
